baseURL = 'https://mathisdesaulty.github.io/ctf-writeups/'
languageCode = 'fr'
title = 'CTF Write-ups'
theme = 'terminal'

[params]
  contentTypeName = "writeups"
  themeColor = "green"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  
[params.logo]
  logoText = "$ ctf-writeups"
  logoHomeLink = "/"

[[params.social]]
  name = "github"
  url = "https://github.com/mathisdesaulty"

[menu]
  [[menu.main]]
    identifier = "writeups"
    name = "Write-ups"
    url = "/writeups/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
